server:
  port: 8080

spring:
  application:
    name: smart-medical

  # MySQL 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smart_medical?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root

  # Redis
  data:
    redis:
      host: localhost
      port: 6379

  # 导入外部密钥配置
  config:
    import: application-secret.yml

# MyBatis-Plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
